server:
  port: 8000

spring:
  application:
    name: todolist
  datasource:
    url: jdbc:postgresql://localhost:5432/todosdb
    username: serverside
    password: serverside
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update